name: urate-db

# ================================================================
# MV BASE DE DATOS — Solo BDs oficiales de Docker Hub.
# No necesita código fuente ni build.
# Solo necesita: este archivo + la carpeta mysql-init/
#
# Uso:
#   docker compose up -d
# ================================================================

networks:
  db_net:
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
  mongo_data:

services:

  postgres:
    image: postgres:16-alpine          # imagen oficial, no custom
    container_name: utec_auth_db
    restart: unless-stopped
    networks: [db_net]
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:8.0                   # imagen oficial, no custom
    container_name: utec_academic_db
    restart: unless-stopped
    networks: [db_net]
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_utec_2025
      MYSQL_DATABASE:      academic_db
      MYSQL_USER:          utec_user
      MYSQL_PASSWORD:      utec_pass_2025
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uutec_user", "-putec_pass_2025"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s

  mongo:
    image: mongo:7                     # imagen oficial, no custom
    container_name: utec_reviews_db
    restart: unless-stopped
    networks: [db_net]
    ports:
      - "0.0.0.0:27017:27017"
    environment:
      MONGO_INITDB_DATABASE: reviews_db
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
